### ISSUE TITLE
How to use multiple HIDUINO devices in windows 7 with Ableton live?

### ISSUE THREAD

**Issue by tshone** [ddiakopoulos/hiduino#14]
Hello,
I have successfully been using the HIDUINO setup now and have 3 devices all with different names that all show up in device manager with that new name.  The problem is, in Windows 7, in Ableton Live, the devices are not different, they all have the name of one of the devices with #1, #2, etc. appended on the end.  Is there a way to have each device have a unique identifier embedded somehow?
Thanks
Tristan

**Comment by camilozk** [comment]
same here!!!

thanks dimitri for sharing this.

![untitled-1](https://cloud.githubusercontent.com/assets/9517856/12898877/21c2c460-ceaf-11e5-8bd0-bfd9fafbda20.jpg)
