### ISSUE TITLE
Schematic for flashing chip not on an arduino?

### ISSUE THREAD

**Issue by thenetimp** [ddiakopoulos/hiduino#19]
Hello,

I have successfully programmed an arduino uno with these hex files. on a 16u2 based uno.  I have gone out and purchased a couple 16u2 chips, and had wired them up based on the datasheet.  I even tried to wire them up based on the Arduino schematic.  I unfortunately unable to get them to accept programming.  I was hoping maybe you've tried this and may have a schematic that works  Thoughts?

**Comment by ddiakopoulos** [comment]
Not sure! The most simple circuit I know for the 16u2 is this:

http://arduino.cc/en/Main/USBSerial

**Comment by thenetimp** [comment]
Looks similar to what I tried  I'll have to try again this weekend. Thanks.
