### ISSUE TITLE
Compile latest version against LUFA

### ISSUE THREAD

**Issue by ibanman555** [ddiakopoulos/hiduino#22]
Has anyone been able to compile the latest version of Hiduino here with LUFA? I've seen that we have recently updated (v2.0?) but I am struggling to compile from scratch to customize the devices names! Help please!

**Comment by diegoherranz** [comment]
I can compile with the latest LUFA version (140928) without problems.

Can you detail your problems? What errors do you get, etc.?

**Comment by ddiakopoulos** [comment]
Closing for lack of further information
