### ISSUE TITLE
Flip: "Address out of range"

### ISSUE THREAD

**Issue by manmon42** [ddiakopoulos/hiduino#24]
I am trying to flash the firmware on my Arduino UNO rev3 using Atmel Flip. Whenever I try and import the .hex file into the program, it throws the error "Address is out of range." I have looked around online and haven't found any solution. Any and all info would be helpful.

**Comment by dturner** [comment]
I was also experiencing this issue and found that my UNO board has an atmega328p chip on it, rather than the at90usb82 as specified in the README. To fix this just change your avrdude command line from `-p at90usb82` to `-p atmega328p`

**Comment by ddiakopoulos** [comment]
I'll notate this in the readme

**Comment by arturobrice** [comment]
address is out of range???? help me please
