### ISSUE TITLE
Mega2560 is not recognised as USB-MIDI device 

### ISSUE THREAD

**Issue by Carlos10240** [ddiakopoulos/hiduino#31]
Hello,

I compiled the arduino_midi again with my name"carlos-midi' and flashed with a Mega2560 using atmel studio on Win7 64 bit.

![1](https://cloud.githubusercontent.com/assets/13554899/10263082/e31a5f30-6a12-11e5-8aea-19a0dc196a93.jpg)
![2](https://cloud.githubusercontent.com/assets/13554899/10263083/e31d155e-6a12-11e5-9146-19f3a448e367.jpg)
![3](https://cloud.githubusercontent.com/assets/13554899/10263084/e320b830-6a12-11e5-9530-0a254644dd2a.jpg)
![4](https://cloud.githubusercontent.com/assets/13554899/10263085/e320d09a-6a12-11e5-8cc8-2aa70f0bf156.jpg)
![5](https://cloud.githubusercontent.com/assets/13554899/10263086/e321e520-6a12-11e5-8b06-4e505e03cfc7.jpg)
![6](https://cloud.githubusercontent.com/assets/13554899/10263087/e3224542-6a12-11e5-8218-e2008e903540.jpg)
![7](https://cloud.githubusercontent.com/assets/13554899/10263088/e349eade-6a12-11e5-9041-2eaa889fe3c2.jpg)

All went smoothly, but still get Mega2560 when plugin.

I hereby attached the process in order:
1.	Plugin avrispmkII
2.	preparing atmel studio
3.	setting fuse
4.	setting lock bit
5.	flash and verify
6.	plugin USB
7.	Arduino Mega 2560 in Device manager

I would need your help to develop a usable usb-midi device with Arduino, but now I get stuck at the first stage, what should I do?

Thanks a lot,

Carlos

**Comment by diegoherranz** [comment]
You have to flash the other Atmel chip on the board, the ATMEGA16U2/8U2 which is the one doing the USB-serial conversion and not the main one. Connect the avrispmkII to the other header connector, the one close to the USB port and try again.

Cheers!

**Comment by Carlos10240** [comment]
Oh yes!  I follow your instruction and successfully see carlos_midi when plugin!  Now I know it is the atmega16U2 doing the USB-serial conversion but not the Atmega2560.

However, that make me confuse.  Would you please tell me when I program the arduino with sketches(pde), am I programming the Atmega16U2 or the Atmega2560?

Later, when I am going to develop that "carlos_midi" USB with sketches, should I refresh the atmega16U2 with its original hex everytime?

Carlos

**Comment by diegoherranz** [comment]
> However, that make me confuse. Would you please tell me when I program the arduino with sketches(pde), am I programming the Atmega16U2 or the Atmega2560?

The Atmega2560. The Atmega16U2 just performs the USB-serial conversion (or USB-MIDI in this case).

> Later, when I am going to develop that "carlos_midi" USB with sketches, should I refresh the atmega16U2 with its original hex everytime?

To program the Atmega2560 using the standard procedure, you would need to flash the Atmega16U2 with the standard serial-USB HEX every time, which is a pain. Another option is connecting the avrispmkII to the ISP header of the Atmega2560 (the header you used the first time) and flash it directly without bootloader. You will need to flash the booloader back to the Atmega2560 to go back to normal operation. Instructions here: https://www.arduino.cc/en/Hacking/Programmer

This is described too on this project's README: https://github.com/ddiakopoulos/hiduino#quickstart
