### ISSUE TITLE
USB Host?

### ISSUE THREAD

**Issue by FredFronky** [ddiakopoulos/hiduino#37]
Hi,
I'm attempting to build a wireless MIDI link. I have the wireless part down, and I can send MIDI out on the receiver, but I'm looking for a way to input USB MIDI to the transmitter.
Essentially, I have an [EWI USB](http://www.akaipro.com/product/ewiusb), which is a class compliant USB MIDI device, and I want to read the MIDI out from it on the Arduino. The problem is twofold. I need to power the EWI somehow, and I need some kind of MIDI host.
Is this possible with HIDUINO, or should I be looking elsewhere.
I did see [this](http://shiftmore.blogspot.com.au/2010/01/quick-and-dirty-arduino-midi-over-usb.html) post, which discussed using a bought converter to create serial MIDI, which I could read, but the device is designed to be plugged into a computer, so I'm not sure about that.
Would the USB Host shield be my best bet her?. The MIDI documentation seems rather sparse for that.
Is there any way to do what I want with this firmware?
Thanks for you help,
Daniel

**Comment by ddiakopoulos** [comment]
Correct about the need for MIDI host functionality. This is been on my far-field todo list for a few years now, but I'm not sure I'll ever get around to it. 

I would recommend investigating the USB Host shield + related software:  https://github.com/felis/USB_Host_Shield_2.0 -- I suspect it might be the only viable option for you (also with MIDI support from this library: https://github.com/YuuichiAkagawa/USBH_MIDI)
